POST http://localhost:3000/api/services 
Content-Type: application/json

{
      "name": "Decoração",
      "description": "Escolha a decoração para sua festa, e nós a montamos.",
      "price": 1400,
      "image": "https://images.unsplash.com/photo-1478146059778-26028b07395a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=892&q=80"
    }

### 
GET http://localhost:3000/api/services/

### 
GET http://localhost:3000/api/services/63937bd13b8bae81ab9c6b6d

### 
DELETE http://localhost:3000/api/services/63937bd13b8bae81ab9c6b6d

### 
PUT http://localhost:3000/api/services/63937bfec4263b463389ec4f 
Content-Type: application/json

{
"name": "ATUALIZADO", "description": "Muito bom", "price": 199.90
}

###

POST http://localhost:3000/api/parties
Content-Type: application/json

{
    "title": "Meu evento2",
    "author": "Jacoby",
    "description": "Uma festa",
    "budget": 3000,
    "image": "https://images.unsplash.com/photo-1478146059778-26028b07395a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=892&q=80",
    "services": [
        {
            "name": "Algum serviço 1", 
            "description": "Alguma descrição.", 
            "price": 3000, "image": "https://images.unsplash.com/photo-1478146059778-26028b07395a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=892&q=80"
        },
        {
            "name": "Algum serviço 2", 
            "description": "Alguma descrição 2", 
            "price": 1600, "image": "https://images.unsplash.com/photo-1478146059778-26028b07395a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=892&q=80"
        }
    ]
}

###

GET http://localhost:3000/api/parties


###

GET http://localhost:3000/api/parties/65a94b156da76d0466e25519

###

DELETE http://localhost:3000/api/parties/65a94b156da76d0466e25519

###

PUT http://localhost:3000/api/parties/65a94b156da76d0466e25519
Content-Type: application/json

{
    "title": "Meu evento",
    "author": "Jacoby",
    "description": "Uma festa",
    "budget": 8000,
    "image": "https://images.unsplash.com/photo-1478146059778-26028b07395a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=892&q=80",
    "services": [
        {
            "name": "Algum serviço 1", 
            "description": "Alguma descrição.", 
            "price": 3000, "image": "https://images.unsplash.com/photo-1478146059778-26028b07395a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=892&q=80"
        },
        {
            "name": "Algum serviço 2", 
            "description": "Alguma descrição 2", 
            "price": 1600, "image": "https://images.unsplash.com/photo-1478146059778-26028b07395a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=892&q=80"
        }
    ]
}